Repository tkeel-io/tkeel, pull requests merged in 2022-02, with the labels that each got.

#90 fix encoding bug
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token_http.pb.go
  api/entity/v1/error.pb.go
  api/entry/v1/entry.pb.go
  api/entry/v1/entry_http.pb.go
  api/entry/v1/error.pb.go
  api/oauth2/v1/error.pb.go
  api/oauth2/v1/oauth2.pb.go
  api/oauth2/v1/oauth2_http.pb.go
  api/plugin/v1/error.pb.go
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/rbac/v1/error.pb.go
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/repo.pb.go
  api/repo/v1/repo_http.pb.go
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/error.pb.go
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant_http.pb.go
  pkg/client/util.go
  pkg/service/keel_v1.go
Labels: approved, lgtm, ok-to-test, size/L

#91 optimize repo
  Makefile
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/plugin/v1/plugin_grpc.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/error.proto
  api/repo/v1/error_errors.pb.go
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  cmd/rudder/root.go
  pkg/hub/hub.go
  pkg/repository/helm/helm.go
  pkg/repository/helm/helm_test.go
  pkg/repository/helm/index.go
  pkg/repository/helm/installer.go
  pkg/repository/repository.go
  pkg/service/common.go
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
  pkg/service/service_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#92 fix bugs
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  pkg/hub/hub.go
  pkg/repository/helm/installer.go
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/XL

#93 fix repo interface
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/repo/v1/repo_grpc.pb.go
  api/repo/v1/repo_http.pb.go
  api/rudder.v1.swagger.json
  cmd/rudder/root.go
  pkg/model/proute/state.go
  pkg/repository/helm/helm.go
  pkg/repository/helm/index.go
  pkg/repository/helm/installer.go
  pkg/repository/repository.go
  pkg/service/authentication_v1.go
  pkg/service/common.go
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
  pkg/service/service_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#94 modify proto field name
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  pkg/repository/helm/helm.go
  pkg/service/repo_v1.go
Labels: bug, approved, lgtm, ok-to-test, size/L

#95 Fix/security
  api/authentication/v1/authentication.pb.go
  api/authentication/v1/error.pb.go
  api/entity/v1/entity_token.pb.go
  api/entity/v1/error.pb.go
  api/entry/v1/entry.pb.go
  api/entry/v1/error.pb.go
  api/oauth2/v1/error.pb.go
  api/oauth2/v1/oauth2.pb.go
  api/plugin/v1/error.pb.go
  api/plugin/v1/plugin.pb.go
  api/rbac/v1/error.pb.go
  api/rbac/v1/rbac.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/repo.pb.go
  api/rudder.v1.swagger.json
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/tenant/v1/error.pb.go
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  api/tenant/v1/tenant_grpc.pb.go
  api/tenant/v1/tenant_http.pb.go
  pkg/service/authentication_v1.go
  pkg/service/oauth_v1.go
  pkg/service/tenant_v1.go
Labels: approved, lgtm, size/XXL

#96 fix bug
  api/authentication/v1/authentication.pb.go
  api/authentication/v1/error.pb.go
  api/entity/v1/entity_token.pb.go
  api/entity/v1/error.pb.go
  api/entry/v1/entry.pb.go
  api/entry/v1/error.pb.go
  api/oauth2/v1/error.pb.go
  api/oauth2/v1/oauth2.pb.go
  api/plugin/v1/error.pb.go
  api/plugin/v1/plugin.pb.go
  api/rbac/v1/error.pb.go
  api/rbac/v1/rbac.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/oauth.pb.go
  api/tenant/v1/error.pb.go
  api/tenant/v1/tenant.pb.go
  charts/tkeel-plugin-components/templates/plugin_config.yaml
  charts/tkeel-plugin-components/templates/plugin_oauth2.yaml
  pkg/repository/helm/index.go
  pkg/repository/repository.go
  pkg/service/authentication_v1.go
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
Labels: approved, lgtm, ok-to-test, size/XXL

#99 fix:add search user by keywords
  go.mod
  go.sum
  pkg/service/tenant_v1.go
Labels: size/M

#101 fix bugs
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  pkg/repository/helm/helm.go
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/XXL

#102 feat/oidc provider
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/security_oauth/v1/oauth_grpc.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/service/oauth_v1.go
Labels: size/XXL

#103 modify API
  api/authentication/v1/authentication_http.pb.go
  api/entity/v1/entity_token_http.pb.go
  api/entry/v1/entry_http.pb.go
  api/oauth2/v1/oauth2_http.pb.go
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/plugin/v1/plugin_http.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/repo/v1/repo_http.pb.go
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/tenant_http.pb.go
  go.mod
  go.sum
  pkg/client/openapi/client.go
  pkg/client/openapi/invoke.go
  pkg/client/util.go
  pkg/model/model.go
  pkg/repository/helm/annotation.go
  pkg/repository/helm/installer.go
  pkg/service/authentication_v1.go
  pkg/service/common.go
  pkg/service/keel/v1/handler.go
  pkg/service/keel/v1/http.go
  pkg/service/keel_v1.go
  pkg/service/plugin_v1.go
  pkg/util/model.go
  pkg/version/version.go
  third_party/openapi/v1/openapi.proto
Labels: approved, lgtm, ok-to-test, size/XXL

#104 fix:provider oidc
  go.mod
  go.sum
  pkg/service/oauth_v1.go
Labels: size/S

#105 Fix/bug
  go.mod
  go.sum
  pkg/service/keel/v1/http.go
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/M

#106 feat: adjust the middleware configuration format
  charts/keel/Chart.yaml
  charts/keel/templates/deployment.yaml
  charts/keel/values.yaml
  charts/rudder/Chart.yaml
  charts/rudder/templates/deployment.yaml
  charts/rudder/values.yaml
  cmd/keel/root.go
  cmd/rudder/root.go
  pkg/config/config.go
Labels: approved, lgtm, size/M

#107 Fix(api):tenant
  api/rudder.v1.swagger.json
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  api/tenant/v1/tenant_grpc.pb.go
  api/tenant/v1/tenant_http.pb.go
  go.mod
  go.sum
  pkg/service/plugin_v1.go
  pkg/service/tenant_v1.go
Labels: size/XXL

#110 Fix/security
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  pkg/service/tenant_v1.go
Labels: size/XL

#109 Feat/permission
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/rbac/v1/error.pb.go
  api/rbac/v1/error.proto
  api/rbac/v1/error_errors.pb.go
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rbac/v1/rbac_grpc.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/rudder.v1.swagger.json
  cmd/rudder/root.go
  go.mod
  pkg/client/dapr/client.go
  pkg/client/dapr/invoke.go
  pkg/client/openapi/invoke.go
  pkg/client/util.go
  pkg/config/config.go
  pkg/hub/error.go
  pkg/model/kv/operator.go
  pkg/model/kv/state.go
  pkg/model/model.go
  pkg/model/plugin/operator.go
  pkg/model/prepo/operator.go
  pkg/model/prepo/state.go
  pkg/model/proute/operator.go
  pkg/repository/helm/helm.go
  pkg/repository/repository.go
  pkg/service/authentication_v1.go
  pkg/service/common.go
  pkg/service/entity_token_v1.go
  pkg/service/entry_v1.go
  pkg/service/keel/v1/http.go
  pkg/service/keel_v1.go
  pkg/service/oauth2_v1.go
  pkg/service/plugin_v1.go
  pkg/service/rbac_v1.go
  pkg/service/rbac_v1_old.go.bak
  pkg/service/repo_v1.go
  pkg/service/tenant_v1.go
  pkg/token/token.go
  pkg/util/http.go
  pkg/util/model.go
  pkg/util/permission_set.go
  pkg/util/version.go
Labels: approved, lgtm, size/XXL

#112 Feat(api):TokenRevoke
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/security_oauth/v1/oauth_grpc.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  pkg/service/oauth_v1.go
Labels: size/XL

#113 Fix/security
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/security_oauth/v1/oauth_grpc.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  go.mod
  go.sum
  pkg/service/tenant_v1.go
Labels: approved, lgtm, size/XXL

#115 feat(api):update password
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  go.mod
  go.sum
  pkg/service/oauth_v1.go
  pkg/service/rbac_v1.go
  pkg/service/tenant_v1.go
Labels: size/L

#116 fix api bugs
  go.mod
  go.sum
  pkg/model/model.go
  pkg/service/authentication_v1.go
  pkg/service/plugin_v1.go
  pkg/service/rbac_v1.go
  pkg/service/repo_v1.go
  pkg/util/permission_set.go
Labels: approved, lgtm, size/L

#117 update chart
  charts/keel/Chart.yaml
  charts/keel/values.yaml
  charts/rudder/Chart.yaml
  charts/rudder/values.yaml
  pkg/service/oauth2_v1.go
Labels: approved, size/S

#118 fix(api):tenant
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  pkg/service/tenant_v1.go
Labels: size/XXL

#119 Add GetRole API
  .gitignore
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rbac/v1/rbac_grpc.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/rudder.v1.swagger.json
  charts/keel/values.yaml
  charts/rudder/values.yaml
  charts/tkeel-plugin-components/Chart.yaml
  pkg/service/rbac_v1.go
Labels: approved, lgtm, size/XXL

#120 Fix/api tenant
  api/rudder.v1.swagger.json
  api/tenant/v1/error.pb.go
  api/tenant/v1/error.proto
  api/tenant/v1/error_errors.pb.go
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  pkg/service/tenant_v1.go
Labels: size/XXL

#121 fix bugs
  go.mod
  pkg/service/rbac_v1.go
Labels: approved, lgtm, size/XS

#122 fix error and chart
  api/authentication/v1/error.pb.go
  api/authentication/v1/error.proto
  api/authentication/v1/error_errors.pb.go
  api/entry/v1/error.pb.go
  api/entry/v1/error.proto
  api/entry/v1/error_errors.pb.go
  api/oauth2/v1/error.pb.go
  api/oauth2/v1/error.proto
  api/oauth2/v1/error_errors.pb.go
  api/plugin/v1/error.pb.go
  api/plugin/v1/error.proto
  api/plugin/v1/error_errors.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/error.proto
  api/repo/v1/error_errors.pb.go
  api/tenant/v1/error.pb.go
  api/tenant/v1/error.proto
  api/tenant/v1/error_errors.pb.go
  charts/keel/templates/deployment.yaml
  charts/keel/values.yaml
  charts/rudder/templates/deployment.yaml
  charts/rudder/values.yaml
  pkg/service/plugin_v1.go
  pkg/service/rbac_v1.go
Labels: approved, lgtm, size/L

#123 fix oauth2 pwd
  pkg/service/oauth2_v1.go
Labels: approved, size/XS

#124 Fix/api reset pwd => rspwd
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/security_oauth/v1/oauth_http.pb.go
Labels: size/L

#125 fix entry
  pkg/client/util.go
  pkg/service/entry_v1.go
  pkg/service/service_test.go
Labels: approved, lgtm, size/L

#126 fix bug
  pkg/model/model.go
  pkg/service/entry_v1.go
  pkg/service/service_test.go
  pkg/service/tenant_v1.go
  pkg/util/model.go
Labels: approved, lgtm

#127 fix bug
  pkg/model/model.go
  pkg/service/common.go
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/XS

#128 fix repo init panic
  pkg/hub/hub.go
Labels: approved, lgtm, size/XS
