Repository tkeel-io/tkeel, pull requests merged in 2022-04, with the labels that each got.

#173 Fix/errorcode
  api/authentication/v1/authentication.pb.go
  api/authentication/v1/authentication_grpc.pb.go
  api/authentication/v1/authentication_http.pb.go
  api/authentication/v1/error.pb.go
  api/config/v1/config.pb.go
  api/config/v1/config_grpc.pb.go
  api/config/v1/config_http.pb.go
  api/config/v1/error.pb.go
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token_grpc.pb.go
  api/entity/v1/entity_token_http.pb.go
  api/entity/v1/error.pb.go
  api/entry/v1/entry.pb.go
  api/entry/v1/entry_grpc.pb.go
  api/entry/v1/entry_http.pb.go
  api/entry/v1/error.pb.go
  api/oauth2/v1/error.pb.go
  api/oauth2/v1/oauth2.pb.go
  api/oauth2/v1/oauth2_grpc.pb.go
  api/oauth2/v1/oauth2_http.pb.go
  api/plugin/v1/error.pb.go
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin_grpc.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/profile/v1/error.pb.go
  api/profile/v1/plgprofile.pb.go
  api/profile/v1/plgprofile_grpc.pb.go
  api/profile/v1/plgprofile_http.pb.go
  api/rbac/v1/error.pb.go
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac_grpc.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/repo.pb.go
  api/repo/v1/repo_grpc.pb.go
  api/repo/v1/repo_http.pb.go
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth_grpc.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/error.pb.go
  api/tenant/v1/error.proto
  api/tenant/v1/error_errors.pb.go
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant_grpc.pb.go
  api/tenant/v1/tenant_http.pb.go
  go.mod
  go.sum
  pkg/service/tenant_v1.go
Labels: size/L

#175 feat: add docs route
  charts/tkeel-middleware/templates/ingress.yaml
Labels: size/S

#176 Feat/ci
  Jenkinsfile
  docker/keel/Dockerfile
  docker/rudder/Dockerfile
Labels: size/L

#185 Fix/idprovider
  api/rudder.v1.swagger.json
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  pkg/service/oauth_v1.go
  pkg/service/tenant_v1.go
Labels: size/XXL

#177 [WIP] ci test
  Jenkinsfile
Labels: size/XS, do-not-merge/work-in-progress

#187 feat:metrics test
  api/metrics/v1/metrics_http.pb.go
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  cmd/rudder/root.go
  pkg/service/metrics.go
  pkg/service/oauth_v1.go
Labels: size/XL
