Repository tkeel-io/tkeel, pull requests merged in 2022-01, with the labels that each got.

#67 Feat: auto inject dapr annotations
  .github/workflows/main.yml
  .github/workflows/public_call.yml
  .github/workflows/push_image.yaml
  .golangci.yml
  OWNERS
  api/entry/v1/entry_http.pb.go
  api/oauth2/v1/oauth2_http.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/repo/v1/repo_http.pb.go
  charts/rudder/test.yaml
  go.mod
  go.sum
  pkg/model/model.go
  pkg/repository/helm/annotation.go
  pkg/repository/helm/helm.go
  pkg/repository/helm/helm_test.go
  pkg/repository/helm/installer.go
  pkg/repository/helm/kustomize.go
  pkg/repository/helm/post_renderer.go
  pkg/repository/helm/testdata/test.yaml
  pkg/service/keel_v1.go
Labels: approved, size/XL, ok-to-test

#66 feat:security0.3.0
  api/apidocs.swagger.json
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token.proto
  api/entity/v1/entity_token_grpc.pb.go
  api/entity/v1/entity_token_http.pb.go
  api/entity/v1/error.pb.go
  api/entity/v1/error.proto
  api/entity/v1/error_errors.pb.go
  api/rbac/v1/error.pb.go
  api/rbac/v1/error.proto
  api/rbac/v1/error_errors.pb.go
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rbac/v1/rbac_grpc.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/security_oauth/apidocs.swagger.json
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/error.proto
  api/security_oauth/v1/error_errors.pb.go
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/security_oauth/v1/oauth_grpc.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/error.pb.go
  api/tenant/v1/error.proto
  api/tenant/v1/error_errors.pb.go
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  api/tenant/v1/tenant_grpc.pb.go
  api/tenant/v1/tenant_http.pb.go
  cmd/rudder/root.go
  go.mod
  go.sum
  id_rsa
  id_rsa.pem
  pkg/config/config.go
  pkg/service/entity_token_v1.go
  pkg/service/keel_v1.go
  pkg/service/oauth_v1.go
  pkg/service/rbac_v1.go
  pkg/service/tenant_v1.go
  third_party/google/api/field_behavior.proto
Labels: approved, lgtm, ok-to-test, size/XXL

#68 Feat:Integrate security
  .github/workflows/main.yml
  .github/workflows/push_image.yaml
  .github/workflows/release_published.yaml
  api/apidocs.swagger.json
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token.proto
  api/entity/v1/entity_token_grpc.pb.go
  api/entity/v1/entity_token_http.pb.go
  api/entity/v1/error.pb.go
  api/entity/v1/error.proto
  api/entity/v1/error_errors.pb.go
  api/rbac/v1/error.pb.go
  api/rbac/v1/error.proto
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rbac/v1/rbac_http.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/error.proto
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  api/security_oauth/apidocs.swagger.json
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/error.proto
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/error.pb.go
  api/tenant/v1/error.proto
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  api/tenant/v1/tenant_http.pb.go
  pkg/service/entity_token_v1.go
  pkg/service/rbac_v1.go
Labels: approved, lgtm, ok-to-test, size/XXL

#73 fix: authenticate with keel
  cmd/keel/root.go
  pkg/service/keel_v1.go
Labels: approved, lgtm, size/M

#78 fix bug
  pkg/config/config.go
Labels: approved

#80 fix:security mod version
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#81 feat: add chart value and fix bugs
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/workflows/main.yml
  Makefile
  charts/rudder/templates/deployment.yaml
  charts/rudder/values.yaml
  pkg/config/config.go
  pkg/service/keel_v1.go
  pkg/service/plugin_v1.go
Labels: approved, lgtm, ok-to-test, size/L

#83 fix:security api
  api/tenant/v1/error.pb.go
  api/tenant/v1/error.proto
  api/tenant/v1/error_errors.pb.go
  cmd/keel/root.go
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/service/oauth_v1.go
  pkg/service/tenant_v1.go
Labels: approved, lgtm, size/L

#85 fix(api):user&tenant api field
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  api/tenant/v1/tenant_grpc.pb.go
  api/tenant/v1/tenant_http.pb.go
  go.mod
  go.sum
  pkg/service/tenant_v1.go
Labels: size/XXL

#86 fix bug
  pkg/service/plugin_v1.go
Labels: approved, lgtm, ok-to-test, size/S

#88 fix bugs
  go.sum
  pkg/client/openapi/invoke.go
  pkg/client/util.go
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/S

#87 feat: authentication and entry menu
  api/authentication/v1/authentication.pb.go
  api/authentication/v1/authentication.proto
  api/authentication/v1/authentication_grpc.pb.go
  api/authentication/v1/authentication_http.pb.go
  api/authentication/v1/error.pb.go
  api/authentication/v1/error.proto
  api/authentication/v1/error_errors.pb.go
  api/rudder.v1.swagger.json
  cmd/keel/root.go
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/client/util.go
  pkg/service/authentication_v1.go
  pkg/service/keel_v1.go
  pkg/service/oauth2_v1.go
  pkg/service/oauth_v1.go
  third_party/openapi/v1/openapi.proto
Labels: approved, lgtm, size/XXL
