Repository tkeel-io/tkeel, pull requests merged in 2022-07, with the labels that each got.

#234 init tenants profile metrics
  pkg/service/profile_v1.go
Labels: approved, lgtm, size/S

#235 fix get prtofile data with tenantID
  pkg/service/profile_v1.go
Labels: approved, lgtm, size/XS

#232 feat: inject oauth2 with file
  pkg/repository/helm/helm.go
  pkg/repository/helm/installer.go
  pkg/repository/helm/plugin.go
Labels: approved, lgtm, size/L

#237 feat: 修改kafka和es的配置参数
  charts/tkeel-middleware/values.yaml
Labels: size/S

#238 fix call notifications with header
  api/entry/v1/notification_http.go
  pkg/repository/repository.go
  pkg/service/entry_v1.go
Labels: approved, lgtm, size/XS

#239 fix plugin route parse
  pkg/service/entry_v1.go
Labels: approved, lgtm, size/M

#240 fix some jira bug
  api/tenant/v1/error.pb.go
  api/tenant/v1/error.proto
  api/tenant/v1/error_errors.pb.go
  pkg/service/tenant_v1.go
Labels: approved, lgtm, size/M

#243 fix delete role
  pkg/service/rbac_v1.go
Labels: approved, lgtm, size/XS

#245 fix
  pkg/service/rbac_v1.go
  pkg/service/tenant_v1.go
Labels: approved, lgtm, size/XS

#246 feat: add tkeel-install-config
  charts/tkeel-middleware/templates/configmap.yaml
Labels: size/M

#241 feat: plugin auto register
  cmd/rudder/root.go
  pkg/register/register.go
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/L

#247 fix:image pullPolicy
  charts/keel/values.yaml
  charts/rudder/values.yaml
Labels: approved, lgtm, size/XS

#248 feat: dont show enable button
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/rudder.v1.swagger.json
  go.mod
  go.sum
  pkg/util/model.go
Labels: approved, lgtm, size/XL

#249 feat: update image pull policy
  cmd/rudder/root.go
  pkg/repository/helm/installer.go
Labels: approved, size/M
