Repository tkeel-io/tkeel, pull requests merged in 2022-03, with the labels that each got.

#130 fix bug
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  pkg/repository/helm/helm.go
  pkg/repository/helm/index.go
  pkg/repository/repository.go
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
  pkg/util/model.go
Labels: approved, lgtm, size/XL

#133 feat: Allow fields to be modified to be empty
  pkg/service/rbac_v1.go
  pkg/service/rbac_v1_old.go.bak
Labels: approved, lgtm, size/L

#134 fix: sort entry
  pkg/service/entry_v1.go
Labels: approved, lgtm, size/XS

#132 Fix/api tenant
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  pkg/service/oauth_v1.go
  pkg/service/tenant_v1.go
Labels: size/XXL

#135 feat configmap
  api/config/v1/config.pb.go
  api/config/v1/config.proto
  api/config/v1/config_grpc.pb.go
  api/config/v1/config_http.pb.go
  api/config/v1/error.pb.go
  api/config/v1/error.proto
  api/config/v1/error_errors.pb.go
  api/rudder.v1.swagger.json
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/client/kubernetes/client.go
  pkg/config/config.go
  pkg/service/config.go
Labels: approved, lgtm, size/XL

#137 Fix/identify enable
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/plugin/v1/plugin_grpc.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/rudder.v1.swagger.json
  go.mod
  go.sum
  pkg/model/model.go
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/XL

#138 fix rbac
  pkg/service/rbac_v1.go
Labels: approved, lgtm, size/XS

#139 fix rbac
  api/rbac/v1/error.pb.go
  api/rbac/v1/error.proto
  api/rbac/v1/error_errors.pb.go
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rudder.v1.swagger.json
  pkg/service/common.go
  pkg/service/rbac_v1.go
Labels: approved, lgtm, size/XL

#140 fix: config add port
  api/config/v1/config.pb.go
  api/config/v1/config.proto
  api/rudder.v1.swagger.json
  pkg/service/config.go
Labels: approved, lgtm, size/M

#141 feat: update chart
  charts/keel/Chart.yaml
  charts/keel/values.yaml
  charts/rudder/Chart.yaml
  charts/rudder/values.yaml
  charts/tkeel-plugin-components/Chart.yaml
Labels: approved, lgtm, size/S

#143 fix: plugin clone
  pkg/model/model.go
Labels: approved, lgtm, size/M

#144 feat: add tm register plugin API
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/plugin/v1/plugin_grpc.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/rudder.v1.swagger.json
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/XL

#145 fix cors and panic
  pkg/model/model.go
  pkg/service/keel/v1/http.go
Labels: approved, lgtm, size/S

#146 fix: user delete
  Makefile
  pkg/service/tenant_v1.go
Labels: approved, lgtm, size/S

#147 Fix/api tenant
  api/authentication/v1/authentication_http.pb.go
  api/config/v1/config_http.pb.go
  api/entity/v1/entity_token_http.pb.go
  api/entry/v1/entry_http.pb.go
  api/oauth2/v1/oauth2_http.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/repo/v1/repo_http.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/tenant_http.pb.go
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/service/oauth_v1.go
Labels: size/L

#149 feat:add redirect url
  go.mod
  go.sum
  pkg/client/dapr/invoke.go
  pkg/service/oauth_v1.go
Labels: size/S

#148 [wip] add feat-jk
  Jenkinsfile
Labels: size/M, do-not-merge/work-in-progress

#150 fix:rbac rol`s id
  pkg/service/rbac_v1.go
Labels: size/XS

#151 update tkeel-middleware chart
  charts/tkeel-middleware/.helmignore
  charts/tkeel-middleware/Chart.lock
  charts/tkeel-middleware/Chart.yaml
  charts/tkeel-middleware/README_zh.md
  charts/tkeel-middleware/charts/elasticsearch-17.8.0.tgz
  charts/tkeel-middleware/charts/etcd-6.10.4.tgz
  charts/tkeel-middleware/charts/kafka-15.3.2.tgz
  charts/tkeel-middleware/charts/nginx-ingress-controller-9.1.5.tgz
  charts/tkeel-middleware/templates/_helpers.tpl
  charts/tkeel-middleware/templates/configmap.yaml
  charts/tkeel-middleware/templates/core-broker-pubsub.keel-system.component.yaml
  charts/tkeel-middleware/templates/core-pubsub.keel-system.component.yaml
  charts/tkeel-middleware/templates/ingress.yaml
  charts/tkeel-middleware/templates/redis-store-core.yaml
  charts/tkeel-middleware/templates/redis_store.yaml
  charts/tkeel-middleware/values.yaml
Labels: size/XL

#155 [test] remove tag
  Jenkinsfile
  charts/keel/values.yaml
Labels: size/S

#157 fix:response token when needn't redirect
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  pkg/service/oauth_v1.go
Labels: size/XL

#159 fix oidc provider
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/service/oauth_v1.go
Labels: size/S

#160 fix charts namespace
  charts/tkeel-middleware/templates/configmap.yaml
  charts/tkeel-middleware/templates/core-broker-pubsub.keel-system.component.yaml
Labels: size/XS

#162 feat: add upgrade plugin
  api/plugin/v1/error.pb.go
  api/plugin/v1/error.proto
  api/plugin/v1/error_errors.pb.go
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/plugin/v1/plugin_grpc.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/rudder.v1.swagger.json
  pkg/model/model.go
  pkg/repository/helm/installer.go
  pkg/repository/repository.go
  pkg/service/oauth_v1.go
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/XXL

#165 fix bugs
  pkg/client/util.go
  pkg/repository/helm/kustomize.go
  pkg/repository/helm/post_renderer.go
  pkg/service/authentication_v1.go
  pkg/service/entry_v1.go
  pkg/service/keel_v1.go
  pkg/service/plugin_v1.go
  pkg/service/rbac_v1.go
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/L

#166 feat(api): profile
  api/profile/v1/error.pb.go
  api/profile/v1/error.proto
  api/profile/v1/error_errors.pb.go
  api/profile/v1/plgprofile.pb.go
  api/profile/v1/plgprofile.proto
  api/profile/v1/plgprofile_grpc.pb.go
  api/profile/v1/plgprofile_http.pb.go
  api/rudder.v1.swagger.json
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/error.proto
  api/security_oauth/v1/error_errors.pb.go
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/model/model.go
  pkg/model/plgprofile/profile_operator.go
  pkg/model/plgprofile/profile_state.go
  pkg/service/oauth_v1.go
  pkg/service/profile_v1.go
  third_party/openapi/v1/openapi.proto
Labels: size/XXL

#167 fix bug
  pkg/repository/helm/kustomize.go
  pkg/repository/helm/post_renderer.go
Labels: approved, lgtm, size/M

#168 fix sort version
  api/authentication/v1/authentication.pb.go
  api/authentication/v1/authentication_grpc.pb.go
  api/authentication/v1/authentication_http.pb.go
  api/authentication/v1/error.pb.go
  api/config/v1/config.pb.go
  api/config/v1/config_grpc.pb.go
  api/config/v1/config_http.pb.go
  api/config/v1/error.pb.go
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token_grpc.pb.go
  api/entity/v1/entity_token_http.pb.go
  api/entity/v1/error.pb.go
  api/entry/v1/entry.pb.go
  api/entry/v1/entry_grpc.pb.go
  api/entry/v1/entry_http.pb.go
  api/entry/v1/error.pb.go
  api/oauth2/v1/error.pb.go
  api/oauth2/v1/oauth2.pb.go
  api/oauth2/v1/oauth2_grpc.pb.go
  api/oauth2/v1/oauth2_http.pb.go
  api/plugin/v1/error.pb.go
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin_grpc.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/profile/v1/error.pb.go
  api/profile/v1/plgprofile.pb.go
  api/profile/v1/plgprofile_grpc.pb.go
  api/profile/v1/plgprofile_http.pb.go
  api/rbac/v1/error.pb.go
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac_grpc.pb.go
  api/rbac/v1/rbac_http.pb.go
  api/repo/v1/error.pb.go
  api/repo/v1/repo.pb.go
  api/repo/v1/repo_grpc.pb.go
  api/repo/v1/repo_http.pb.go
  api/security_oauth/v1/error.pb.go
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth_grpc.pb.go
  api/security_oauth/v1/oauth_http.pb.go
  api/tenant/v1/error.pb.go
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant_grpc.pb.go
  api/tenant/v1/tenant_http.pb.go
  go.mod
  go.sum
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/L

#169 fix: TM register plugin force delete plugin route
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/XS

#171 fix: entry merge
  pkg/service/entry_v1.go
  pkg/service/service_test.go
Labels: approved, lgtm, size/M

#172 feat: update middleware max kafka message size
  charts/tkeel-middleware/templates/core-broker-pubsub.keel-system.component.yaml
  charts/tkeel-middleware/templates/core-pubsub.keel-system.component.yaml
Labels: size/XS
