Repository tkeel-io/tkeel, pull requests merged in 2022-06, with the labels that each got.

#216 feat: tkeel-middleware add tkeel-metrics.yaml
  charts/tkeel-middleware/templates/tkeel-metrics.yaml
Labels: approved, lgtm, size/S

#218 fix: build containers with makefile & chart`s service yaml support tkeelio/prometheus
  Makefile
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token.proto
  api/entity/v1/error.pb.go
  api/entity/v1/error.proto
  api/entity/v1/error_errors.pb.go
  api/rudder.v1.swagger.json
  charts/keel/templates/service.yaml
  charts/rudder/templates/service.yaml
  cmd/rudder/root.go
  keel.yml
  pkg/model/model.go
  pkg/model/plgprofile/keel_profile.go
  pkg/service/authentication_v1.go
  pkg/service/entity_token_v1.go
  pkg/service/profile_v1.go
  rudder.yml
  third_party/openapi/v1/openapi.proto
Labels: approved, lgtm, size/L

#222 fix api docs
  api/authentication/v1/authentication.pb.go
  api/authentication/v1/authentication.proto
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token.proto
  api/profile/v1/plgprofile.pb.go
  api/profile/v1/plgprofile.proto
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  pkg/service/authentication_v1.go
  third_party/openapi/v1/openapi.proto
Labels: approved, lgtm

#223 chore:upgrade kit log
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#224 Update values.yaml
  charts/tkeel-middleware/values.yaml
Labels: approved, lgtm, size/XS

#225 fix:profile
  api/authentication/v1/authentication.pb.go
  api/authentication/v1/authentication.proto
  api/config/v1/config.pb.go
  api/config/v1/config.proto
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token.proto
  api/oauth2/v1/oauth2.pb.go
  api/oauth2/v1/oauth2.proto
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/profile/v1/plgprofile.pb.go
  api/profile/v1/plgprofile.proto
  api/profile/v1/plgprofile_grpc.pb.go
  api/profile/v1/plgprofile_http.pb.go
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  cmd/rudder/root.go
  go.mod
  go.sum
  pkg/model/model.go
  pkg/model/plgprofile/keel_profile.go
  pkg/model/plgprofile/profile_operator.go
  pkg/model/plgprofile/profile_state.go
  pkg/service/authentication_v1.go
  pkg/service/profile_v1.go
  third_party/openapi/v1/openapi.proto
Labels: approved, lgtm, size/XXL

#226 fix:profile
  api/entity/v1/entity_token.pb.go
  api/entity/v1/entity_token.proto
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/profile/v1/plgprofile.pb.go
  api/profile/v1/plgprofile.proto
  api/rbac/v1/rbac.pb.go
  api/rbac/v1/rbac.proto
  api/rudder.v1.swagger.json
  api/security_oauth/v1/oauth.pb.go
  api/security_oauth/v1/oauth.proto
  api/tenant/v1/tenant.pb.go
  api/tenant/v1/tenant.proto
  pkg/model/plgprofile/keel_profile.go
  pkg/model/plgprofile/profile_state.go
  pkg/service/profile_v1.go
Labels: approved, lgtm, size/XXL

#227 feat: update docs comment
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
Labels: size/XXL

#228 feat: admin enable & disable plugin for tenant
  api/plugin/v1/plugin.pb.go
  api/plugin/v1/plugin.proto
  api/plugin/v1/plugin_grpc.pb.go
  api/plugin/v1/plugin_http.pb.go
  api/rudder.v1.swagger.json
  pkg/service/plugin_v1.go
Labels: approved, lgtm, size/XXL

#230 Refactor/profile
  cmd/rudder/root.go
  pkg/model/metrics/collector.go
  pkg/service/profile_v1.go
Labels: approved, lgtm, size/S

#231 fix metrics collector
  cmd/rudder/root.go
Labels: approved, lgtm, size/XS
