Repository tkeel-io/tkeel, pull requests merged in 2022-05, with the labels that each got.

#189 feat: PlatformExtraConfig support muti-key
  api/config/v1/config.pb.go
  api/config/v1/config.proto
  api/config/v1/config_grpc.pb.go
  api/config/v1/config_http.pb.go
  pkg/service/config.go
Labels: approved, lgtm, size/L

#190 fix bug
  go.mod
  go.sum
  pkg/model/plgprofile/keel_profile.go
  pkg/service/config.go
  pkg/service/oauth_v1.go
  pkg/service/profile_v1.go
  pkg/service/tenant_v1.go
Labels: approved, lgtm, ok-to-test, size/L

#191 [WIP] exchange oidc provider identity's external id == userid & try fix lint action
  .github/workflows/public_call.yml
  api/metrics/v1/metrics_http.pb.go
  cmd/rudder/root.go
  pkg/model/plgprofile/keel_profile.go
  pkg/service/oauth_v1.go
Labels: lgtm, size/L

#196 feat: repo support harbor helm repository
  .golangci.yml
  pkg/repository/helm/index.go
Labels: size/M

#197 Fix(proto):regenerate config proto.go
  api/config/v1/config_http.pb.go
  api/rudder.v1.swagger.json
Labels: size/L

#198 feat: add "latest" version
  pkg/repository/helm/index.go
Labels: approved, lgtm, ok-to-test, size/S

#200 platform-extra-config-support-muti-key
  api/config/v1/config.pb.go
  api/config/v1/config.proto
  api/config/v1/config_grpc.pb.go
  api/config/v1/config_http.pb.go
  go.mod
  go.sum
  pkg/service/config.go
Labels: approved, lgtm, ok-to-test, size/XXL

#201 Platform config
  go.mod
  go.sum
  pkg/service/config.go
  pkg/service/keel_v1.go
Labels: approved, lgtm, ok-to-test, size/XXL

#204 feat:support harbor
  devops/Jenkinsfile
  devops/config/ci.yaml
  devops/config/test.yaml
  devops/scripts/kotb.py
Labels: size/L

#205 fix: devops
  devops/Jenkinsfile
Labels: size/L

#210 feat: increased body size to 2M
  charts/tkeel-middleware/templates/ingress.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#212 chore: devops
  devops/Jenkinsfile
Labels: size/L

#209 feat: installer add version_list
  api/repo/v1/repo.pb.go
  api/repo/v1/repo.proto
  api/rudder.v1.swagger.json
  pkg/repository/helm/helm.go
  pkg/repository/repository.go
  pkg/service/plugin_v1.go
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/XXL

#215 feat: repo installer list always return latest version
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/S

#217 fix: installed count incorrect
  pkg/service/repo_v1.go
Labels: approved, lgtm, size/XS
